- name: Asegurar que el paquete apache2 este instalado
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
  tags: apache

- name: Desplegar index.html personalizado desde plantilla
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: Reiniciar apache2
  tags: apache

- name: Asegurar que el servicio apache2 este inciado y habilitado en el arranque
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  tags: apache

